{{- if .Values.appConfigmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-chart.fullname" . }}
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.appConfigmap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }} 