{{- if and (not .Values.cronJob.enabled) (not .Values.scaledJob.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-chart.fullname" . }}
  labels:
    {{- include "base-chart.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "base-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: {{ include "base-chart.fullname" . }}-storage
          persistentVolumeClaim:
            claimName: {{ include "base-chart.fullname" . }}-pvc
      {{- end }}
      containers:
        - name: {{ include "base-chart.fullname" . }}
          {{- if and .Values.appConfigmap.enabled .Values.appSecrets.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "base-chart.fullname" . }}
            - secretRef:
                name: {{ include "base-chart.fullname" . }}
          {{- else if .Values.appConfigmap.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "base-chart.fullname" . }}
          {{- else if .Values.appSecrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ include "base-chart.fullname" . }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: 
            {{- range .Values.command }}
              - {{ . }}
            {{- end }}
          {{- end }}
          {{- if .Values.exposes_port }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
            failureThreshold: {{ .Values.probe.liveness.failureThreshold }}
            timeoutSeconds: {{ .Values.probe.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
            failureThreshold: {{ .Values.probe.readiness.failureThreshold }}
            timeoutSeconds: {{ .Values.probe.readiness.timeoutSeconds }}
          {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: {{ include "base-chart.fullname" . }}-storage
              mountPath: {{ .Values.persistence.mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}